<BarcodeScreen>
    id: settings
    name: 'settings'
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Button:
            text: 'Capture code'
            size_hint_y: None
            height: '80dp'
            on_press:
                root.BarcodeReader()
        Label:
            id: my_label
            size: root.width, root.height
            font_size: 20
        Label:
            id: my_label2
            size: (0.5, 0.5)
            font_size: 20
